#!/usr/bin/env python3
"""上傳影片到 YouTube(預設 private,per-channel)。

用法:
  python scripts/youtube_upload.py --channel tech                        # tech 頻道最新的影片
  python scripts/youtube_upload.py --channel embedded --file 指定檔.mp4  # 指定檔案
  python scripts/youtube_upload.py --privacy unlisted --title "自訂標題"

標題預設: "<title_prefix> - <top1 新聞標題>"。輸出: output/<slug>/youtube_upload.json。
"""

import json
import sys
import time
from pathlib import Path

import httpx

from _common import channel_dir, fail, flag_value, load_env, resolve_channel, save_json, setup_logging
from _youtube import ensure_access_token

logger = setup_logging("youtube_upload")

UPLOAD_URL = "https://www.googleapis.com/upload/youtube/v3/videos"
CHUNK = 4 * 1024 * 1024  # 4 MB


UPLOADS_RECORD = "youtube_uploads.json"  # 每個頻道目錄內的上傳記錄


def latest_video(cdir: Path) -> Path:
    candidates = sorted(cdir.glob("video_*.mp4"), key=lambda p: p.stat().st_mtime)
    if not candidates:
        fail(logger, f"找不到 {cdir}/video_*.mp4 — 請先執行 scripts/run_video_pipeline.py --channel <slug>")
    return candidates[-1]


def load_upload_records(cdir: Path) -> dict:
    path = cdir / UPLOADS_RECORD
    if path.exists():
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            logger.warning(f"[WARN] {UPLOADS_RECORD} 損壞,重新開始記錄")
    return {}


def build_metadata(cdir: Path, channel: dict, file: Path) -> tuple[str, str]:
    top1_path = cdir / "top1.json"
    prefix = channel.get("title_prefix", "Daily News")
    if top1_path.exists():
        top1 = json.loads(top1_path.read_text(encoding="utf-8"))
        news = top1.get("news", top1)
        title = f"{prefix} - {news.get('title', file.stem)}"
        description_lines = [
            news.get("headline", "") or news.get("summary", ""),
            f"來源: {news.get('source', '')}  {news.get('url', '')}",
            "",
            "由 tech-news-to-video pipeline 自動生成(Gemini 選題 → NotebookLM Video Overview)。",
        ]
        description = "\n".join(description_lines)[:4900]
    else:
        title = f"{prefix} - {file.stem.replace('_', ' ')}"
        description = "Generated by tech-news-to-video pipeline."
    return title[:95], description


def init_upload(access_token: str, size: int, title: str, description: str, privacy: str) -> str:
    resp = httpx.post(
        f"{UPLOAD_URL}?uploadType=resumable&part=snippet,status",
        headers={
            "Authorization": f"Bearer {access_token}",
            "Content-Type": "application/json; charset=UTF-8",
            "X-Upload-Content-Type": "video/mp4",
            "X-Upload-Content-Length": str(size),
        },
        json={
            "snippet": {
                "title": title,
                "description": description,
                "categoryId": "28",  # Science & Technology
                "tags": ["tech news", "notebooklm"],
            },
            "status": {"privacyStatus": privacy, "selfDeclaredMadeForKids": False},
        },
        timeout=60.0,
    )
    if resp.status_code not in (200, 201):
        fail(logger, f"建立上傳 session 失敗 (HTTP {resp.status_code})", resp.text[:1000])
    location = resp.headers.get("Location")
    if not location:
        fail(logger, "回應缺少 Location header", resp.text[:500])
    return location


def upload_body(session_uri: str, file: Path) -> dict:
    def chunks():
        with open(file, "rb") as fh:
            while chunk := fh.read(CHUNK):
                yield chunk

    with httpx.stream(
        "PUT", session_uri, headers={"Content-Type": "video/mp4"}, data=chunks(), timeout=300.0
    ) as resp:
        body = resp.read().decode("utf-8", errors="replace")  # streaming 模式需先 read
        if resp.status_code not in (200, 201):
            fail(
                logger,
                f"上傳失敗 (HTTP {resp.status_code})",
                body[:1000],
            )
        return json.loads(body)


def main() -> None:
    load_env()
    args = sys.argv[1:]
    slug = flag_value(args, "--channel")
    channel = resolve_channel(slug, logger)
    cdir = channel_dir(channel)

    file_arg = flag_value(args, "--file")
    file = Path(file_arg) if file_arg else latest_video(cdir)
    if not file.exists():
        fail(logger, f"影片檔不存在: {file}")
    privacy = flag_value(args, "--privacy", "private")
    custom_title = flag_value(args, "--title")
    force = "--force" in args

    # 防重複上傳: 同檔名已有記錄就跳過(--force 可覆蓋)
    records = load_upload_records(cdir)
    if file.name in records and not force:
        rec = records[file.name]
        logger.info(f"[INFO] {file.name} 已上傳過,跳過(用 --force 強制重傳): {rec.get('url', rec.get('video_id'))}")
        return

    size = file.stat().st_size
    logger.info(f"[INFO] 頻道 {channel['slug']}: 影片 {file} ({size / 1024 / 1024:.1f} MB),privacy={privacy}")

    access_token = ensure_access_token(logger)
    title, description = build_metadata(cdir, channel, file)
    if custom_title:
        title = custom_title[:95]
    logger.info(f"[INFO] 標題: {title}")

    session_uri = init_upload(access_token, size, title, description, privacy)
    logger.info("[INFO] 上傳中(36 MB 約 1-3 分鐘)...")
    result = upload_body(session_uri, file)

    video_id = result.get("id")
    if not video_id:
        fail(logger, "上傳回應缺少 video id", json.dumps(result, ensure_ascii=False)[:1000])
    records[file.name] = {
        "video_id": video_id,
        "url": f"https://youtu.be/{video_id}",
        "title": title,
        "privacy": privacy,
        "uploaded_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    save_json(records, cdir / UPLOADS_RECORD)
    logger.info(f"[PASS] 上傳完成: https://youtu.be/{video_id} (privacy={privacy})")


if __name__ == "__main__":
    main()
